testnet-config:
  consensus-layer:
      preset-base: 'mainnet'
      capella-fork-epoch: 0
      deneb-fork-epoch: 1
      min-genesis-active-validator-count: 60
      disable-peer-scoring: true


consensus-configs:
  grandine-consensus-client:
    num-validators: 20
    log-level: 'info'
  lighthouse-consensus-client:
    num-validators: 20
    log-level: 'info'
  prysm-consensus-client:
    num-validators: 20
    log-level: 'info'
  lodestar-consensus-client:
    num-validators: 20
    log-level: 'info'
  nimbus-consensus-client:
    num-validators: 20
    log-level: 'info'
  teku-consensus-client:
    num-validators: 20
    log-level: 'info'


execution-configs:
  reth-execution-config:
    log-level: 'vvv'
  nethermind-execution-config:
    log-level: 'info'
  geth-execution-config:
    log-level: '4'
  besu-execution-config:
    log-level: 'info'

client-instances:
  prysm-geth:
    image: "etb-all-clients"
    tag: "dencun"
    start-ip-address: "10.0.20.10"
    num-nodes: 1
    consensus-config: "prysm-consensus-client"
    execution-config: "geth-execution-config"
    validator-offset-start: 0
    mock-builder: 1
  lighthouse-nethermind:
    image: "etb-all-clients"
    tag: "dencun"
    start-ip-address: "10.0.20.20"
    num-nodes: 1
    consensus-config: "lighthouse-consensus-client"
    execution-config: "nethermind-execution-config"
    validator-offset-start: 20
    mock-builder: 1
  nimbus-reth:
    image: "etb-all-clients"
    tag: "dencun"
    start-ip-address: "10.0.20.30"
    num-nodes: 1
    consensus-config: "nimbus-consensus-client"
    execution-config: "reth-execution-config"
    validator-offset-start: 40
    mock-builder: 1

generic-instances:
    assertoor:
      image: "etb-all-clients"
      tag: "dencun"
      start-ip-address: "10.0.20.220"
      num-nodes: 1
      entrypoint: "/usr/local/bin/assertoor"
      command: [
        "-v",
        "--log-format",
        "json",
        "--config=/data/assertoor-config.yaml",
      ]
      ports: ["8080:8080", "9082:9090"]
