id: workload-blob
name: "generate random blob transactions"
schedule:
  startup: false
timeout: 1m
tasks:
- name: generate_blob_transactions
  title: "Generate 3 blob transactions per block"
  config:
    childWallets: 5
    limitPending: 12
    limitPerBlock: 6
    randomTarget: true
    amount: 1000000
    randomAmount: true
    blobSidecars: 3
    limitTotal: 18
  configVars:
    privateKey: "walletPrivkey"