testnet-config:
  consensus-layer:
    preset-base: 'minimal'
    capella-fork-epoch: 0
    deneb-fork-epoch: 1
    min-genesis-active-validator-count: 60
    disable-peer-scoring: true
consensus-configs:
  lodestar-consensus-client:
    num-validators: 20
    log-level: 'info'
execution-configs:
  besu-execution-config:
    log-level: 'info'
    json-snooper-proxy-port: 8765
client-instances:
  lodestar-besu:
    image: "etb-all-clients-minimal"
    tag: "pectra"
    start-ip-address: "10.0.20.10"
    num-nodes: 3
    consensus-config: "lodestar-consensus-client"
    execution-config: "besu-execution-config"
    validator-offset-start: 0
generic-instances:
  assertoor:
    image: "etb-all-clients-minimal"
    tag: "pectra"
    start-ip-address: "10.0.20.220"
    num-nodes: 1
    entrypoint: "/usr/local/bin/assertoor"
    command: ["-v", "--log-format", "json", "--config=/data/assertoor-config.yaml"]
    ports: ["8080:8080", "9082:9090"]
